### ISSUE TITLE
Hex

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/bbox#2]
Sir,

I am taking down my repo with the same name, but wondered if you could find some use for the logo I designed for it.

**Comment by sckott** [comment]
👋 @dmi3kno - sorry about the name conflict, was the repo the same topic as this repo?  Or different?  

that's a nice sticker, i'd be happy to use that. if the topic of your repo was the same perhaps you want to help with code?

**Comment by dmi3kno** [comment]
I am dealing with bounding boxes in image domain: those produced by HOCR (in `tesseract`) and geometries in `magick`. So yes, similar and different at the same time. My `bbox`es are strings in the format `xmin ymin xmax ymax` sometimes comma-separated, but more often just space-separated. Geometries in `magick` are `WxH+X+Y`(offsets), which can be translated back into `bbox`. Another are are Hough lines in magick. They are reported exactly like text boxes above, except the opposite corners of the box mean beginning and end of the line. Also fascinating object type.
Yes, please do use the logo. I will PR reproducible example for making the logo into your `tools` folder, if you don't mind. And a copy of image into `man/figures` for use on README.

**Comment by sckott** [comment]
thanks for the info. Sounds good.

**Comment by dmi3kno** [comment]
I see you did not adopt the logo. I am spinning off my image-bbox functions to a new package `bbx` and I am going to re-use the logo. Sorry, had to pull my gift back ;) Cheers and good luck!

**Comment by sckott** [comment]
no worries, sounds good!
